# Generated by Django 4.1.2 on 2022-10-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='all_news',
            field=models.TextField(default=1000),
            preserve_default=False,
        ),
    ]
