# Generated by Django 4.1.5 on 2023-01-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_trans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сarrier',
            new_name='Carrier',
        ),
    ]
